// src/app/components/about/about.component.ts
import { Component } from '@angular/core';
import { FadeInDirective } from '../../directives/fade-in.directive';

@Component({
  selector: 'app-about',
  standalone: true,
  imports: [FadeInDirective],
  templateUrl: './about.component.html',
  styleUrl: './about.component.css'
})
export class AboutComponent {}

<section id="about" class="about" appFadeIn>
  <div class="container">
    <h2>About Us</h2>
    <p>Welcome to Chess Academy, where passion meets strategy. Our experienced instructors are dedicated to nurturing chess talent at all levels, from beginners taking their first steps to advanced players seeking to refine their skills.</p>
    <p>Whether you prefer learning in a group setting or desire personalized one-to-one attention, we have the perfect program for you. Join our community of chess enthusiasts and embark on your journey to chess mastery.</p>
  </div>
</section>

// src/components/About.jsx
export default function About() {
  return (
    <section id="about" className="about">
      <div className="container">
        <h2>About Us</h2>
        <p>
          Welcome to Chess Academy, where passion meets strategy. Our experienced
          instructors are dedicated to nurturing chess talent at all levels, from
          beginners taking their first steps to advanced players seeking to refine
          their skills.
        </p>
        <p>
          Whether you prefer learning in a group setting or desire personalized
          one-to-one attention, we have the perfect program for you. Join our
          community of chess enthusiasts and embark on your journey to chess mastery.
        </p>
      </div>
    </section>
  );
}
