// src/app/components/footer/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  standalone: true,
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.css'
})
export class FooterComponent {
  protected currentYear = new Date().getFullYear();
}

<footer class="footer">
  <div class="container">
    <div class="footer-content">
      <div class="footer-brand">
        <p>&copy; {{ currentYear }} Chess Academy. All rights reserved.</p>
      </div>
      <div class="footer-social">
        <a href="#" aria-label="Facebook">FB</a>
        <a href="#" aria-label="Twitter">TW</a>
        <a href="#" aria-label="Instagram">IG</a>
      </div>
    </div>
  </div>
</footer>

// src/components/Footer.jsx
export default function Footer() {
  return (
    <footer className="footer">
      <div className="container">
        <div className="footer-content">
          <div className="footer-brand">
            <p>&copy; 2024 Chess Academy. All rights reserved.</p>
          </div>
          <div className="footer-social">
            <a href="#" aria-label="Facebook">FB</a>
            <a href="#" aria-label="Twitter">TW</a>
            <a href="#" aria-label="Instagram">IG</a>
          </div>
        </div>
      </div>
    </footer>
  );
}
