// src/app/components/header/header.component.ts
import { Component, HostListener, signal } from '@angular/core';

@Component({
  selector: 'app-header',
  standalone: true,
  templateUrl: './header.component.html',
  styleUrl: './header.component.css'
})
export class HeaderComponent {
  protected menuOpen = signal(false);

  toggleMenu(): void {
    this.menuOpen.update(value => !value);
    document.body.style.overflow = this.menuOpen() ? 'hidden' : '';
  }

  closeMenu(): void {
    this.menuOpen.set(false);
    document.body.style.overflow = '';
  }

  @HostListener('document:click', ['$event'])
  onDocumentClick(event: MouseEvent): void {
    const target = event.target as HTMLElement;
    const isClickInsideNav = target.closest('.nav-menu') || target.closest('.nav-toggle');

    if (!isClickInsideNav && this.menuOpen()) {
      this.closeMenu();
    }
  }

  scrollTo(event: Event, targetId: string): void {
    event.preventDefault();
    this.closeMenu();

    const targetElement = document.querySelector(targetId);
    if (targetElement) {
      const header = document.querySelector('.header');
      const headerHeight = header ? header.clientHeight : 0;
      const targetPosition = targetElement.getBoundingClientRect().top + window.scrollY - headerHeight;

      window.scrollTo({
        top: targetPosition,
        behavior: 'smooth'
      });
    }
  }
}

<header class="header">
  <nav class="nav">
    <div class="nav-brand">
      <a href="#home" (click)="scrollTo($event, '#home')">Chess Academy</a>
    </div>
    <button
      class="nav-toggle"
      [class.active]="menuOpen()"
      aria-label="Toggle navigation"
      (click)="toggleMenu(); $event.stopPropagation()"
    >
      <span class="hamburger"></span>
    </button>
    <ul class="nav-menu" [class.active]="menuOpen()">
      <li><a href="#home" class="nav-link" (click)="scrollTo($event, '#home')">Home</a></li>
      <li><a href="#courses" class="nav-link" (click)="scrollTo($event, '#courses')">Courses</a></li>
      <li><a href="#about" class="nav-link" (click)="scrollTo($event, '#about')">About</a></li>
      <li><a href="#contact" class="nav-link" (click)="scrollTo($event, '#contact')">Contact</a></li>
    </ul>
  </nav>
</header>

// src/components/Header.jsx
import { useState, useEffect } from 'react';

export default function Header() {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [activeSection, setActiveSection] = useState('home');

  const navLinks = [
    { href: '#home', label: 'Home' },
    { href: '#courses', label: 'Courses' },
    { href: '#about', label: 'About' },
    { href: '#contact', label: 'Contact' },
  ];

  const toggleMenu = () => {
    setIsMenuOpen(!isMenuOpen);
    document.body.style.overflow = !isMenuOpen ? 'hidden' : '';
  };

  const closeMenu = () => {
    setIsMenuOpen(false);
    document.body.style.overflow = '';
  };

  const handleNavClick = (e, href) => {
    e.preventDefault();
    closeMenu();
    const targetId = href.substring(1);
    const targetElement = document.getElementById(targetId);
    if (targetElement) {
      const headerHeight = document.querySelector('.header').offsetHeight;
      const targetPosition = targetElement.offsetTop - headerHeight;
      window.scrollTo({
        top: targetPosition,
        behavior: 'smooth'
      });
    }
  };

  useEffect(() => {
    const handleScroll = () => {
      const sections = document.querySelectorAll('section[id]');
      const scrollPosition = window.scrollY + 100;

      sections.forEach((section) => {
        const sectionTop = section.offsetTop;
        const sectionHeight = section.offsetHeight;
        const sectionId = section.getAttribute('id');

        if (scrollPosition >= sectionTop && scrollPosition < sectionTop + sectionHeight) {
          setActiveSection(sectionId);
        }
      });
    };

    const handleClickOutside = (event) => {
      const navMenu = document.querySelector('.nav-menu');
      const navToggle = document.querySelector('.nav-toggle');
      if (navMenu && navToggle) {
        const isClickInsideNav = navMenu.contains(event.target) || navToggle.contains(event.target);
        if (!isClickInsideNav && isMenuOpen) {
          closeMenu();
        }
      }
    };

    window.addEventListener('scroll', handleScroll);
    document.addEventListener('click', handleClickOutside);
    handleScroll();

    return () => {
      window.removeEventListener('scroll', handleScroll);
      document.removeEventListener('click', handleClickOutside);
    };
  }, [isMenuOpen]);

  return (
    <header className="header">
      <nav className="nav">
        <div className="nav-brand">
          <a href="#home" onClick={(e) => handleNavClick(e, '#home')}>Chess Academy</a>
        </div>
        <button
          className={`nav-toggle ${isMenuOpen ? 'active' : ''}`}
          aria-label="Toggle navigation"
          onClick={toggleMenu}
        >
          <span className="hamburger"></span>
        </button>
        <ul className={`nav-menu ${isMenuOpen ? 'active' : ''}`}>
          {navLinks.map((link) => (
            <li key={link.href}>
              <a
                href={link.href}
                className={`nav-link ${activeSection === link.href.substring(1) ? 'active' : ''}`}
                onClick={(e) => handleNavClick(e, link.href)}
              >
                {link.label}
              </a>
            </li>
          ))}
        </ul>
      </nav>
    </header>
  );
}
