// src/app/components/hero/hero.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-hero',
  standalone: true,
  templateUrl: './hero.component.html',
  styleUrl: './hero.component.css'
})
export class HeroComponent {
  scrollTo(event: Event, targetId: string): void {
    event.preventDefault();
    const targetElement = document.querySelector(targetId);
    if (targetElement) {
      const header = document.querySelector('.header');
      const headerHeight = header ? header.clientHeight : 0;
      const targetPosition = targetElement.getBoundingClientRect().top + window.scrollY - headerHeight;

      window.scrollTo({
        top: targetPosition,
        behavior: 'smooth'
      });
    }
  }
}

<section id="home" class="hero">
  <div class="hero-content">
    <h1>Chess Academy</h1>
    <p class="tagline">Master the Art of Chess with Expert Guidance</p>
    <a href="#courses" class="btn btn-primary" (click)="scrollTo($event, '#courses')">Explore Courses</a>
  </div>
</section>

// src/components/Hero.jsx
export default function Hero() {
  const handleClick = (e) => {
    e.preventDefault();
    const targetElement = document.getElementById('courses');
    if (targetElement) {
      const headerHeight = document.querySelector('.header').offsetHeight;
      const targetPosition = targetElement.offsetTop - headerHeight;
      window.scrollTo({
        top: targetPosition,
        behavior: 'smooth'
      });
    }
  };

  return (
    <section id="home" className="hero">
      <div className="hero-content">
        <h1>Chess Academy</h1>
        <p className="tagline">Master the Art of Chess with Expert Guidance</p>
        <a href="#courses" className="btn btn-primary" onClick={handleClick}>
          Explore Courses
        </a>
      </div>
    </section>
  );
}
